"""The Career Program codified: every Day 1-14 principle turned into an
actionable setup card with context, trigger, risk, invalidation and the
underlying principle - so the trader executes the program, not vibes.
"""

PRINCIPLES = [
    {"day": 1, "topic": "Futures & Options", "rules": [
        "Cut losers fast.",
        "Leverage and maximize conviction-driven winners.",
        "Judge performance on combined key metrics, not win rate alone.",
        "When uncertain: reduce size or don't trade - study so you're ready next time.",
        "Always be aware of environment and context."]},
    {"day": 2, "topic": "Support & Resistance", "rules": [
        "S/R are not created equal - HTF levels matter more but are wider zones.",
        "Bounces: prioritize FIRST touches. Breaks: prefer levels already tested at least once.",
        "S/R reveals other traders' positioning and where they're in danger.",
        "Trendline breaks give quick liquidation scalps without implying trend change.",
        "Approaching a zone, hunt for order-flow change to judge break vs hold."]},
    {"day": 3, "topic": "Chart Patterns", "rules": [
        "Patterns are positioning maps: who is trapped, where is their last defense.",
        "More time + volume compressed with clear invalidation for both sides = more explosive break.",
        "Use the fractal: lower-timeframe entries for higher-timeframe targets.",
        "Read in real time whether the trade is working before the stop does the talking.",
        "Gaps are invisible moves: just-outside-range gap = breakout entry at the open; far-extended gap = profit-taking + fade risk."]},
    {"day": 4, "topic": "Volume & Delta", "rules": [
        "Be more active when absolute volume is high - directional moves live there.",
        "Breakouts: high absolute volume + rising relative volume + fast tape.",
        "Volume spike with no follow-through at an extreme = exhaustion.",
        "Grade S/R strength by the volume/reaction at prior touches; weakening reactions = level likely breaks.",
        "Pre-define how price/volume should behave; deviation = don't enter / get out; stronger than expected = add."]},
    {"day": 5, "topic": "Entry & Exit", "rules": [
        "Organize: never let a scalp become a swing or vice versa.",
        "Scaling-in test: 'would I enter here fresh, with conviction?'",
        "Targets = others' profit-taking/counter-trade locations + order-flow behavior + elapsed time.",
        "Only asymmetric trades. If it's not asymmetric, pass.",
        "No 'free trades' - act on analysis; breakeven stop only under real uncertainty while in profit."]},
    {"day": 6, "topic": "Profile Principles", "rules": [
        "Balance -> imbalance -> balance, fractally. Initiative breaks balance; responsive contains discovery.",
        "Healthy trends absorb pullbacks; enter only after initiative signs.",
        "Time + volume at price = acceptance (value). Track value migration to anticipate.",
        "HVNs get retested; first rejection of prior value is a trade - acceptance back inside means traversal.",
        "LVNs: range edges in balance, acceleration fuel in discovery."]},
    {"day": 7, "topic": "Day Types", "rules": [
        "Poor highs/ledges are targets - find your entry on the way via LTF patterns.",
        "Trend days: small IB, elongated profile, buy absorption pullbacks.",
        "After a trend day expect a balanced day.",
        "P/b liquidation days: position near where balance began, target the middle/other end.",
        "Open inside a prior double distribution: edges of both distributions are S/R - play to the middle."]},
    {"day": 8, "topic": "Opening Plays", "rules": [
        "Prep: how did yesterday trade and close? Where are we opening vs prior value/range?",
        "First hour (IB) sets directional conviction - lean with it unless something changes.",
        "45-degree fat tops/bottoms need less energy to reverse than continue.",
        "Failed auction after a neutral day / volume-heavy range is a top-tier play: defined risk, trapped-trader fuel."]},
    {"day": 9, "topic": "Mapping", "rules": [
        "Christmas-tree profiles = reversal candidates (cousin of fat tops + failed auctions).",
        "Map prior activity religiously - recent and HTF history predicts the battlefield."]},
    {"day": 10, "topic": "Order Flow & Absorption", "rules": [
        "The keyword is RELATIVE CHANGE and where it occurs.",
        "Sudden acceleration after calm = entry clue; acceleration after an extended move = exit clue.",
        "Icebergs give a clear limit: join it, or trade its break - both with defined risk."]},
    {"day": 11, "topic": "Large Orders", "rules": [
        "Always read what the OTHER side is doing before acting on a big order.",
        "If momentum trades straight into a large bid without fear, don't front-run the bid."]},
    {"day": 12, "topic": "Spoofing & Momentum", "rules": [
        "Manipulative ladder games live in quiet, low-volume tape.",
        "Everything is momentum vs absorption: read intent, commitment, surrender, double-down.",
        "Use low-volume pockets to (re)join momentum you missed."]},
    {"day": 13, "topic": "Momentum Reversals", "rules": [
        "Pre-enter breaks of poor highs/ledges on order-flow change en route; stop behind the LVN.",
        "Snap-and-run is a last-resort breakout entry - risk a few ticks behind the snap.",
        "Stop-catching: rest orders behind stop clusters for the blip - exit the moment it stalls.",
        "Crescendo blips after a big move = take profits."]},
    {"day": 14, "topic": "Central Bank Prep", "rules": [
        "Dot plots vs market pricing.",
        "Diff the central-bank language vs the prior statement.",
        "Know exactly what's priced in BEFORE the event.",
        "Know what central bankers care about right now - that's the reaction function."]},
]

SETUPS = [
    {"id": "failed-auction", "name": "Failed Auction Reversal", "day_ref": 8,
     "context": "Neutral/balanced prior day or heavy volume accumulated in a range.",
     "trigger": "Break of range/IB extreme that gets rejected back inside within a few bars.",
     "entry": "On reclaim of the broken level, or first weak retest of it from inside.",
     "stop": "A few ticks beyond the failed extreme.",
     "target": "Other side of the range - trapped traders' liquidation is your fuel.",
     "why": "Defined risk + 'if it wasn't ready to go this way, it goes the other way' + liquidation energy."},
    {"id": "open-drive-gap", "name": "Gap-Outside-Range Open Drive", "day_ref": 3,
     "context": "Open gaps just outside prior range (not extended).",
     "trigger": "Opening minutes confirm: trapped side exiting + breakout side initiating (volume + speed).",
     "entry": "At/near the open, or Globex pre-position while the gap forms if conditions align.",
     "stop": "Back inside prior range beyond the breakout level.",
     "target": "Next HTF level / measured move; trail with LTF structure.",
     "why": "Open concentrates the forced exits and the chasers at the same moment - max liquidity energy."},
    {"id": "fade-extended-gap", "name": "Extended Gap Fade", "day_ref": 3,
     "context": "Open gaps FAR from prior range, ideally into a strong HTF supply/demand zone.",
     "trigger": "Profit-taking + responsive activity at the zone (exhaustion volume, no follow-through).",
     "entry": "Against the gap direction at the zone with order-flow confirmation.",
     "stop": "Beyond the zone.", "target": "Gap fill toward prior range edge.",
     "why": "Positioned winners cash out at the open; extension + HTF zone attracts responsive sellers/buyers."},
    {"id": "prior-value-rejection", "name": "First Rejection of Prior Value", "day_ref": 6,
     "context": "Price returns to test a prior HVN/value area for the FIRST time.",
     "trigger": "Clear responsive reaction at VAH/VAL - declining momentum into the level, counter-flow.",
     "entry": "At the value edge.", "stop": "Inside value past the POC re-acceptance point.",
     "target": "Back toward where price came from / next LVN.",
     "why": "HVN retests are expected; the first rejection has the cleanest trapped-trader geometry."},
    {"id": "value-traversal", "name": "Value Area Traversal", "day_ref": 6,
     "context": "Price re-enters prior value and STAYS (time + volume inside).",
     "trigger": "Acceptance: rotations building inside value rather than rejecting.",
     "entry": "On the pullback after re-entry.", "stop": "Back outside the value edge.",
     "target": "Traverse the whole value area to the other extreme.",
     "why": "Acceptance inside value means the market will usually auction across the full agreed zone."},
    {"id": "lvn-breakout", "name": "LVN Acceleration Break", "day_ref": 6,
     "context": "Balance edge sits at a low-volume node; market in discovery mood (check GEX regime).",
     "trigger": "Initiative volume + fast tape into/through the LVN (Day 4 conditions).",
     "entry": "Through the LVN or pre-entry on order-flow change approaching it (Day 13).",
     "stop": "Behind the LVN.", "target": "Beginning of next HVN / prior value.",
     "why": "No volume = no argument: price accelerates across vacuum until the next acceptance area."},
    {"id": "poor-high-magnet", "name": "Poor High/Low Break", "day_ref": 7,
     "context": "Unfinished auction (flat, multi-TPO extreme) above/below current trade.",
     "trigger": "Find an LTF entry (flag break, structure break) on the WAY to the poor extreme.",
     "entry": "LTF breakout with momentum.", "stop": "Behind LTF structure / LVN.",
     "target": "Through the poor extreme - often with acceleration as resting stops trigger.",
     "why": "Poor extremes are magnets; entering en route gives asymmetric R:R into a known target."},
    {"id": "trend-pullback", "name": "Trend Day Absorption Pullback", "day_ref": 7,
     "context": "Small IB + elongating one-sided profile = trend day in progress.",
     "trigger": "Shallow pullback showing absorption (passive defense) then initiative resumption.",
     "entry": "On resumption.", "stop": "Below absorption cluster.",
     "target": "Hold a core to the close - trend days close near the extreme; trail with structure.",
     "why": "Healthy trends absorb pullbacks (Day 6); fighting trend days is the #1 account killer."},
    {"id": "liquidation-balance", "name": "P/b Liquidation Day Play", "day_ref": 7,
     "context": "Sharp liquidation then balance forming (P or b profile).",
     "trigger": "Responsive defense at the balance edge nearest the liquidation origin.",
     "entry": "Near the bottom (b) / top (P) of the new balance.", "stop": "Beyond the balance edge.",
     "target": "Middle, then other end of the balance.",
     "why": "Post-liquidation balance defines a tradeable bracket while the market digests."},
    {"id": "stop-catch", "name": "Stop-Run Catch", "day_ref": 13,
     "context": "Fast move approaching an obvious stop cluster (beyond ON high/low, poor extreme, big strike).",
     "trigger": "The blip through the cluster.",
     "entry": "Resting orders just beyond the cluster, against the blip.",
     "stop": "Tight - a few ticks.", "target": "The fast correction only - exit the moment it stalls.",
     "why": "Forced orders overshoot; the snap-back is mechanical. Time-based trade, not a position."},
    {"id": "news-momentum", "name": "Scheduled-News Momentum Join", "day_ref": 14,
     "context": "Clean surprise vs consensus on a tier-1 release (CPI/NFP/FOMC).",
     "trigger": "One-sided repricing: momentum with rising relative volume, weak counter-rotations.",
     "entry": "First pullback showing absorption AFTER the initial burst (don't chase tick one).",
     "stop": "Beyond the pullback's absorption cluster.",
     "target": "Next HTF level; news-driven trades get wider invalidation than scalps (Day 5).",
     "why": "Surprises force multi-day repositioning - you're joining flows that MUST trade."},
]


def get_playbooks() -> dict:
    return {"principles": PRINCIPLES, "setups": SETUPS}
